# .github/workflows/daily-report.yml
name: Daily Report (+ Heartbeat)

on:
  schedule:
    - cron: "7 5 * * *"     # daily at 05:07 UTC
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip requests

      - name: Heartbeat (timestamp)
        run: |
          python scripts/heartbeat.py

      - name: Generate daily README section
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/daily_report.py

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add HEARTBEAT.md README.md
            git commit -m "chore: daily heartbeat + report"
            git push
          else
            echo "No changes to commit."
          fi
